// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/armormeds-hero/AnimeAction.tsx": () => import("../components/mockups/armormeds-hero/AnimeAction.tsx"),
  "./components/mockups/armormeds-hero/BrutalistType.tsx": () => import("../components/mockups/armormeds-hero/BrutalistType.tsx"),
  "./components/mockups/armormeds-hero/ComicPanels.tsx": () => import("../components/mockups/armormeds-hero/ComicPanels.tsx"),
  "./components/mockups/armormeds-hero/CyberpunkNeon.tsx": () => import("../components/mockups/armormeds-hero/CyberpunkNeon.tsx"),
  "./components/mockups/armormeds-hero/ExplosionImpact.tsx": () => import("../components/mockups/armormeds-hero/ExplosionImpact.tsx"),
  "./components/mockups/armormeds-hero/Hologram.tsx": () => import("../components/mockups/armormeds-hero/Hologram.tsx"),
  "./components/mockups/armormeds-hero/LuxuryEditorial.tsx": () => import("../components/mockups/armormeds-hero/LuxuryEditorial.tsx"),
  "./components/mockups/armormeds-hero/OpeningCrawl.tsx": () => import("../components/mockups/armormeds-hero/OpeningCrawl.tsx"),
  "./components/mockups/armormeds-hero/PunchedOut.tsx": () => import("../components/mockups/armormeds-hero/PunchedOut.tsx"),
  "./components/mockups/armormeds-hero/RebelPoster.tsx": () => import("../components/mockups/armormeds-hero/RebelPoster.tsx"),
  "./components/mockups/armormeds-hero/Synthwave80s.tsx": () => import("../components/mockups/armormeds-hero/Synthwave80s.tsx"),
  "./components/mockups/armormeds-hero/Synthwave80sAsymmetric.tsx": () => import("../components/mockups/armormeds-hero/Synthwave80sAsymmetric.tsx"),
  "./components/mockups/armormeds-hero/Synthwave80sCentered.tsx": () => import("../components/mockups/armormeds-hero/Synthwave80sCentered.tsx"),
  "./components/mockups/armormeds-hero/Synthwave80sSplit.tsx": () => import("../components/mockups/armormeds-hero/Synthwave80sSplit.tsx"),
  "./components/mockups/armormeds-hero/WesternOutlaw.tsx": () => import("../components/mockups/armormeds-hero/WesternOutlaw.tsx")
};
