// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/armormeds-hero/ComicPanels.tsx": () => import("../components/mockups/armormeds-hero/ComicPanels.tsx"),
  "./components/mockups/armormeds-hero/ExplosionImpact.tsx": () => import("../components/mockups/armormeds-hero/ExplosionImpact.tsx"),
  "./components/mockups/armormeds-hero/PunchedOut.tsx": () => import("../components/mockups/armormeds-hero/PunchedOut.tsx")
};
